sudo: required
language: generic
services:
  - docker

before-install:
  - docker build -t diraulo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true diraulo/docker-react yarn test -- --coverage
