sudo: required
language: generic
services:
  - docker

before-install:
  - docker build -t diraulo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true diraulo/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "af-south-1"
  app: "docker-react"
  environment: "DockerReact-env"
  bucket_name: "elasticbeanstalk-af-south-1-186522626504"
  bucket_path: "docker-react"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: master
