version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - 4000:3000
    volumes:
      - /app/node_modules
      - .:/app
